---
- name: Add remote server in nagios config
  hosts: all
  vars:
    new_vm_ip: "10.32.170.159"
    new_vm_name: "server1"
    http_listen_port: "80"
    
  tasks:

    - name: Create configuration file (server_id.cfg) for the server
      file:
        path: /etc/nagios/servers/{{ new_vm_name }}.cfg
        state: touch
        
    - name: Add information in config file
      blockinfile:
        dest: /etc/nagios/servers/{{ new_vm_name }}.cfg
        content: |
          define host {
                  use                             linux-server
                  host_name                       {{ new_vm_name }}
                  address                         {{ new_vm_ip }}
                  max_check_attempts              5
                  check_period                    24x7
                  notification_interval           30
                  notification_period             24x7
          }

          define service {
                  use                             local-service
                  host_name                       {{ new_vm_name }}
                  service_description             HTTP_Ansible_Demo
                  check_command                   check_http_with_args!{{ http_listen_port }}!/index.html
                  notifications_enabled           0
                  event_handler                   ansible-playbook
                  check_interval                  0.5
           }
         
    - name: Restart nagios service
      service:
        name: nagios
        state: restarted
        
    
 
        

