---
- name: Add remote server in nagios config
  hosts: all
  vars:
    nagios_remote_server_ip: "10.32.170.152"
    nagios_remote_server_id: "server1"
    http_listen_port: "80"
    
  tasks:

    - name: Insert host in hosts.cfg file
      blockinfile:
        dest: /etc/nagios/object/hosts.cfg
        content: |
          define host {
                  use                             linux-server
                  host_name                       {{ nagios_remote_server_id }}
                  address                         {{ nagios_remote_server_ip }}
                  max_check_attempts              5
                  check_period                    24x7
                  notification_interval           30
                  notification_period             24x7
          }
