---
- name: Add remote server in nagios config
  hosts: all
  vars:
    nagios_remote_server_ip: "10.32.170.152"
    nagios_remote_server_id: "server1"
    http_listen_port: "80"
    
  tasks:

    - name: Check hosts.cfg, services.cfg and commands.cfg files exist
      file:
        path: 
        state: present
        
    - name: Insert host in hosts.cfg file
      blockinfile:
        dest: /etc/nagios/object/hosts.cfg
        content: |
          define host {
                  use                             linux-server
                  host_name                       {{ nagios_remote_server_id }}
                  address                         {{ nagios_remote_server_ip }}
                  max_check_attempts              5
                  check_period                    24x7
                  notification_interval           30
                  notification_period             24x7
          }
    
    - name: Insert host in services.cfg file
      blockinfile:
        dest: /etc/nagios/object/services.cfg
        content: |
          define host {
                  use                             local-service
                  host_name                       {{ nagios_remote_server_id }}
                  service_description             HTTP_Ansible_Demo
                  check_command			              check_http_with_args!{{ http_listen_port }}!/test.html
                  notifications_enabled		        0
                  event_handler			              ansible-playbook
                  check_interval			            0.5
           }
                     }
    
    - name: Insert commands in commands.cfg file
      blockinfile:
        dest: /etc/nagios/object/commands.cfg
        content: |
            define command{
                  command_name    check_http_with_args
                  command_line    $USER1$/check_http -I $HOSTADDRESS$ -p $ARG1$ -u $ARG2$
            }
            define command{
                  command_name	ansible-playbook
                  command_line	/usr/local/nagios/etc/servers/ansible-playbook.bash $SERVICESTATE$ $SERVICESTATETYPE$ $SERVICEATTEMPT$ $HOSTNAME$
            }
            
        

