---
- hosts: all
  user: root
  vars:
    node_address: 192.168.121.123
    node_hostname: fakehost.example.demo
  tasks:
  - name: Gather facts
    setup:

  - name: Update /etc/hosts from host list
    lineinfile: 
       dest=/etc/hosts
       regexp="^{{node_address}}" 
       line='{{node_address}} {{node_hostname}}' 
       state=present

