---
- name: Add remote server in nagios config
  hosts: all
  vars:
    nagios_remote_server_ip: "10.32.170.152"
    nagios_remote_server_id: "server1"
    http_listen_port: "80"
    
  tasks:

    - name: Create configuration file (server_id.cfg) for the server
      file:
        path: /etc/nagios/servers/"{{ nagios_remote_server_id }}".cfg
        state: touch
        
    - name: Add information in config file
      blockinfile:
        dest: /etc/nagios/servers/"{{ nagios_remote_server_id }}".cfg
        content: |
          define host {
                  use                             linux-server
                  host_name                       {{ nagios_remote_server_id }}
                  address                         {{ nagios_remote_server_ip }}
                  max_check_attempts              5
                  check_period                    24x7
                  notification_interval           30
                  notification_period             24x7
          }

          define host {
                  use                             local-service
                  host_name                       {{ nagios_remote_server_id }}
                  service_description             HTTP_Ansible_Demo
                  check_command			              check_http_with_args!{{ http_listen_port }}!/index.html
                  notifications_enabled		        0
                  event_handler			              ansible-playbook
                  check_interval			            0.5
           }
                   
    
 
        

