---
- name: Install and start Apache HTTPD
  hosts: all

  tasks:
    - name: httpd package is present
      yum:
        name: httpd
        state: present

    - name: correct index.html is present
      blockinfile:
        dest: /var/www/html/index.html
        create: yes
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        insertafter: "<body>"
        content: |
          <h1>Welcome to {{ ansible_hostname }}</h1>
          <p>Last updated on {{ ansible_date_time.iso8601 }}</p>
          
    - name: httpd is started
      service:
        name: httpd
        state: started
        enabled: true
        
    - name: install php
      yum:
        name: php
        state: latest      
        
    - name: Changing perm of index.php
      file: 
        dest=/var/www/html/index.php
        mode=u+x 
     
    - name: Modifying php index
      copy:
        content: "
          <html>
          <head>
          <title>Welcome to {{ ansible_hostname }}</title>
          </head>
          <body>
          </body>
          </html>"
        dest: /var/www/html/index.php
        force: no

