---
- name: Install and start Apache HTTPD
  hosts: all

  tasks:
    - name: httpd package is present
      yum:
        name: httpd
        state: present

    - name: correct index.html is present
      blockinfile:
        dest: /var/www/html/index.html
        create: yes
        block: |
          wellcome!

    - name: httpd is started
      service:
        name: httpd
        state: started
        enabled: true
