---
- name: Luks application check 
  user: root
  hosts: all
  vars:
     satellite_ip: 10.32.170.134
     satellite_user: admin
     satellite_psw: redhat01
     host_name: host

  tasks:
 #  - name: Check /etc/crypttab contains existence
  #   file:
  #     path: /etc/crypttab
  #     state: absent     
  #   check_mode: yes
  #   register: checkFile
     
   - name: Check wether /etc/crypttab contains "home"
     lineinfile:
       path: /etc/crypttab
       state: absent
       regexp: 'home*'       
     check_mode: yes
     register: homeEncrypted
   
   - name: Check wether /etc/crypttab contains "swap"
     lineinfile:
       path: /etc/crypttab
       state: absent
       regexp: 'swap*'       
     check_mode: yes
     register: swapEncrypted
     
   - name: Delete any encrypted fact in /etc/rhsm/facts/encrypted.facts
     lineinfile:
       path: /etc/rhsm/facts/encrypted.facts
       state: absent
       regexp: 'encrypted*'       
     
   - name: Add fact file encrypted.facts in /etc/rhsm/facts/ as not encypted host if needed
     lineinfile:
       path: /etc/rhsm/facts/encrypted.facts
       state: present
       create: yes
       backup: yes
       line: {"encrypted": "disable"}
          
   - name: Add fact file encrypted.facts in /etc/rhsm/facts/ as encrypted host if that is the case
     replace:
       path: /etc/rhsm/facts/encrypted.facts
       regexp: 'disable'
       replace: 'enable'
     when: (homeEncrypted.changed and swapEncrypted.changed)
    
   - name: Create server_encrypted ansible fact
     set_fact:
       server_encrypted: enabled
     when: (homeEncrypted.changed and swapEncrypted)

   - name: Create temporary file with json structure to send to Satellite by the API
     template:
       src: templates/updated_facts_tmp.json.j2
       dest: /root/updated_facts_tmp.json
       
   - name: Send facts to Satellite
     command: 'curl -X POST -u {{ satellite_user }}:{{ satellite_psw }} -k -H "Content-Type:application/json" -d @/root/updated_facts_tmp.json https://{{ satellite_ip }}/api/v2/hosts/facts'
     
   - name: Delete temporary file
     file:
       path: /root/updated_facts_tmp.json
       state: absent
