---
- name: Luks application check 
  user: root
  hosts: all
  vars:
     satellite_ip: 10.32.170.160
     satellite_user: admin
     satellite_psw: redhat01

  tasks:
 #  - name: Check /etc/crypttab contains existence
  #   file:
  #     path: /etc/crypttab
  #     state: absent     
  #   check_mode: yes
  #   register: checkFile
     
   - name: Check wether /etc/crypttab contains "home"
     lineinfile:
       path: /etc/crypttab
       state: absent
       regexp: 'home*'       
     check_mode: yes
     register: homeEncrypted
   
   - name: Check wether /etc/crypttab contains "home"
     lineinfile:
       path: /etc/crypttab
       state: absent
       regexp: 'swap*'       
     check_mode: yes
     register: swapEncrypted
     
   - name: Delete any encrypted fact in /etc/rhsm/facts/encrypted.facts
     lineinfile:
       path: /etc/rhsm/facts/encrypted.facts
       state: absent
       regexp: 'encrypted*'       
     
   - name: Add fact file encrypted.facts in /etc/rhsm/facts/ as not encypted host if needed
     lineinfile:
       path: /etc/rhsm/facts/encrypted.facts
       state: present
       create: yes
       line: {"encrypted": "no"}
     
   - name: Add fact file encrypted.facts in /etc/rhsm/facts/ as encypted host if that is the case
     replace:
       path: /etc/rhsm/facts/encrypted.facts
       regexp: 'no'
       replace: 'yes'
     when: (homeEncrypted.changed and swapEncrypted)
     
   - name: Format facts to be sent to Satellite
     shell: cat "/var/lib/rhsm/facts/facts.json"
     register: data
     
   - name: Send facts to Satellite
     uri:
       url: http://{{ satellite_ip }}/api/v2/hosts/facts
       method: POST
       user: "{{ satellite_user }}"
       password: "{{ satellite_psw }}"
       body: data
       return_content: no
       validate_certs: no
       HEADER_Content-Type: application/json
       HEADER_Accept: :application/json,version=2
       
       
         
