---
- name: Clear CMDB
  user: root
  hosts: all
  tasks:
   - name: Clear CMDB list
     uri:
        url: "http://ucmdb-jmn-ucmdb.app.labmad.redhat.com/clear.php"
        method: GET
        return_content: no
