---
- name: Install and start Apache HTTPD
  hosts: all
  vars:
    elb_zones: "This is your new apache server"
    index_image: ""

  tasks:
    - name: configure elb 
        local_action:
          module: ec2_elb_lb
          name: "test-please-delete"
          state: present
          #zones:      
          #  - us-east-1d
          listeners:
            - protocol: http
              load_balancer_port: 80
              instance_port: 80
          health_check:
            ping_protocol: http # options are http, https, ssl, tcp
            ping_port: 80
            ping_path: "/index.html" # not required for tcp or ssl
            response_timeout: 5 # seconds
            interval: 30 # seconds
            unhealthy_threshold: 2
            healthy_threshold: 10
