---
- name: "Create node and add it to a pool"
  hosts: 10.32.170.154
  connection: local
  gather_facts: no
  vars:
    host_id: new_host
    f5_password: xxx
    f5_user: admin

  tasks:
    - name: Delete node
      bigip_node:
        provider:
          server: "{{inventory_hostname}}"
          user: "{{f5_user}}"
          password: "{{f5_password}}"
          validate_certs: no
          transport: rest
        name: "{{host_id}}"
        state: absent
      delegate_to: localhost

