---
- name: "Retrieve facts from f5"
  hosts: 10.32.170.154
  connection: local
  gather_facts: no
  vars:
    vip_id: new_vip
    partition_id: Common
    vip_partition_id: /{{partition_id}}/{{vip_id}}
    f5_password: xxx
    f5_user: admin

  tasks:
    - name: Collect BIG-IP facts
      bigip_facts:
        #provider:
        server: "{{inventory_hostname}}"
        user: "{{f5_user}}"
        password: "{{f5_password}}"
        validate_certs: no
        transport: rest
        server_port: 443
        include:
          - virtual_server
        filter: "{{vip_id}}"
      register: bigip_facts
      delegate_to: localhost

    - name: print out the results of ios_facts
      debug:
        #var: bigip_facts['ansible_facts']['virtual_server']['/Common/new_VIP']['default_pool_name']
        msg: "the partition id / vip is like this '{{vip_partition_id}}'"
#        msg: "{{ bigip_facts['ansible_facts']['virtual_server']['/Common/new_VIP']['default_pool_name'] | basename }}"
#        msg: "El pool es el {{ [inventory_hostname]['default_pool_name'] }}"

    


