---
- name: "Add members to a pool"
  hosts: all
  connection: local
  gather_facts: no
  vars:
    pool_id: new_pool
    port_number: 80
    f5_password: xxx
    f5_user: admin
    #node: { host: '10.32.170.159', name: 'node-1' }
  
  tasks:
    - name: Add members to a pool
      bigip_pool_member:
        provider:
          password: "{{f5_password}}"
          server: "{{inventory_hostname}}"
          user: "{{f5_user}}"
          validate_certs: no
          transport: rest
        description: webserver-1
        host: 10.32.170.159
        name: node-1
       # host: "{{ node.host }}"
       # name: "{{ node.name }}"
        pool: "{{pool_id}}"
        port: "{{port_number}}" 
        state: present
      delegate_to: localhost
