---
- name: "Create new VIP from a referenced VIP"
  hosts: all
  connection: local
  gather_facts: no
  vars:
    new_VIP_id: new_VIP
    old_VIP_id: old_VIP
    partition_id: Common
    VIP_partition_VIPid: /{{partition_id}}/{{old_VIP_id}} 
    f5_password: xxx
    f5_user: admin

  tasks:
    - name: Collect VIP facts
      bigip_facts:
        #provider:
        server: "{{inventory_hostname}}"
        user: "{{f5_user}}"
        password: "{{f5_password}}"
        validate_certs: no
        transport: rest
        server_port: 443
        include:
          - virtual_server
        filter: "{{old_VIP_id}}"
      register: bigip_facts
      delegate_to: localhost
      
    - name: Delete VIP
      bigip_virtual_server:
        provider:
          server: "{{inventory_hostname}}"
          user: "{{f5_user}}"
          password: "{{f5_password}}"
          validate_certs: no
          transport: rest
        name: "{{old_VIP_id}}"
        state: absent
      delegate_to: localhost

    - name: Create new VIP from referenced data
      bigip_virtual_server:
        provider:
          server: "{{inventory_hostname}}"
          user: "{{f5_user}}"
          password: "{{f5_password}}"
          validate_certs: no
          transport: rest
        name: "{{new_VIP_id}}"
        pool: "{{ bigip_facts['ansible_facts']['virtual_server'][VIP_partition_VIPid]['default_pool_name'] | basename }}"
        port: "{{ bigip_facts['ansible_facts']['virtual_server'][VIP_partition_VIPid]['destination']['port'] }}"
        description: "{{ bigip_facts['ansible_facts']['virtual_server'][VIP_partition_VIPid]['description'] }}"
        destination: "{{ bigip_facts['ansible_facts']['virtual_server'][VIP_partition_VIPid]['destination']['address'] | basename }}"

#        snat: "{{}}"
#        all_profiles:
#           - http
      delegate_to: localhost


    


