---
- name: set static IP from DHCP configuration
  user: root
  gather_facts: true
  hosts: all
  tasks:
  - name: get facts 
    setup:  

  - name: Node Name
    debug: msg="{{ ansible_nodename }}" 

  - name: IPaddr
    debug: msg="{{ ansible_default_ipv4.address }}" 
