---
- name: Install and start Nagios
  hosts: all
# vars:
#    index_message: "This is your new apache server"
#    index_image: ""

  tasks:
    - name: install nagios
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - nagios
        - nrpe
        - nagios-plugins-all
        - nagios-plugins-nrpe
        - php
        - httpd
 
    - name: start nagios service
      service:
        name: nagios  
        state: started
        enabled: true
   
    - name: start httpd service
      service:
        name: httpd
        state: restarted
        enabled: true
        
    - name: set SELinux permissive mode
      selinux:
        state: permissive
      
