---

- name: Create an instance
  hosts: all
  gather_facts: no
  connection: local
  vars:
    project: my-project
    gcp_cred_kind: serviceaccount
    gcp_cred_file: '{{ lookup("env", "GCE_PEM_FILE_PATH") }}' 
    image: 'projects/rhel-cloud/global/images/rhel-7-v20190116'
    zone: "europe-west1-b"
    region: "europe-west1"
    disk_name: 'disk-instance'
    disk_size_gb: 10
    network_name: 'network-instance'
    address_name: 'address-instance'
    vm_name: 'test-vm'
    instance_state: "present"

  tasks:
    - shell: '/home/student5/ansible-playbook new_vm_GCP.yml'

