---
- name: Prueba set_stats 2
  hosts: localhost
  tasks:
    - name: "Get test results from the web"
      uri:
        url: "{{ prueba_results }}"
        return_content: true
      register: results

    - name: "Output test results"
      debug:
        msg: "{{ results.content }}"
