---
- name: Install Postgres Server
  user: root
  hosts: ansiblecore
  tasks:
   - name: Disable all repos
     command: subscription-manager repos --disable="*"

   - name: Enable RHEL server repos
     command: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms"
