---
- hosts: localhost
  connection: local
  vars:
    # Tokens Bot
    tokenBot: XXX
    # Chat IDs
    chatID: YYY
    telegram_message: "Algo va mal..."

  tasks:
    - name: Sending message to Telegram private chat/group
      telegram: 
         token: '{{ tokenBot }}'
         chat_id: {{ chatID }}
         msg: {{ telegram_message }}
