---
- name: Createa a new VIP
  hosts: all
  connection: local
  gather_facts: no
  vars:
    VIP_id: new_VIP
    destination_IP: x.x.x.x
    pool_id: new_pool
    port_number: 80
    f5_password: xxx
    f5_user: admin
    VIP_description: new app

  tasks:
    - name: Create a VIP
      bigip_virtual_server:
        description: "{VIP_description}}"
        destination: "{{destination_IP}}"
        provider:
          server: "{{inventory_hostname}}"
          user: "{{f5_user}}"
          password: "{{f5_password}}"
          validate_certs: no
          transport: rest
        name: "{{VIP_id}}"
        pool: "{{pool_id}}"
        port: "{{port_number}}" 
#        snat: "{{}}"
        all_profiles:
           - http
      delegate_to: localhost
